# permissions for end users to view namespacelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: namespace-label
    app.kubernetes.io/managed-by: kustomize
  name: namespacelabel-viewer-role
rules:
- apiGroups:
  - namespacelabel.dana.io
  resources:
  - namespacelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - namespacelabel.dana.io
  resources:
  - namespacelabels/status
  verbs:
  - get
